version: '3.7'

networks:
  app-net:

services:
  app:
    build:
      context: .
      dockerfile: .docker/dockerfile
    image: coppel-user-layaway-service_app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8002
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8002:8002
    networks:
      - app-net
