version: '3.7'

networks:
  coppel-challenge-net:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: leonardoalvarezdev20/coppel-user-layaway-service_app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8002
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8002:8002
    networks:
      - coppel-challenge-net
